import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Sidebar principal para toda la documentación
  principal: [
    { type: 'doc',
      id: 'intro',
      label: 'Introducción',
    },
    {
      type: 'category',
      label: 'Lineamientos',
      // link: { type: 'generated-index', title: 'Lineamientos' },
      items: [{ type: 'autogenerated', dirName: 'lineamientos' }],
    },
    {
      type: 'category',
      label: 'ADRs',
      // link: { type: 'generated-index', title: 'ADRs' },
      items: [{ type: 'autogenerated', dirName: 'adrs' }],
    },
    {
      type: 'category',
      label: 'Servicios Corporativos',
      // link: { type: 'generated-index', title: 'Servicios Corporativos' },
      items: [{ type: 'autogenerated', dirName: 'servicios-corporativos' }],
    },
    {
      type: 'category',
      label: 'Aplicaciones',
      // link: { type: 'generated-index', title: 'Aplicaciones' },
      items: [{ type: 'autogenerated', dirName: 'aplicaciones' }],
    },
    {
      type: 'category',
      label: 'Capa de Integración',
      // link: { type: 'generated-index', title: 'Capa de Integración' },
      items: [{ type: 'autogenerated', dirName: 'capa-integracion' }],
    },
    {
      type: 'category',
      label: 'Apéndices',
      // link: { type: 'generated-index', title: 'Apéndices' },
      items: [{ type: 'autogenerated', dirName: 'apendices' }],
    },
  ],
  // Sidebar legacy para compatibilidad con navbar antiguo
  // tutorialSidebar: [
  //   { type: 'category', label: 'Documentación', items: [{ type: 'doc', id: 'intro' }] },
  // ],
};

export default sidebars;
